### ISSUE TITLE
Does this encompass the following feature request (links in the description) ?

### ISSUE THREAD

**Issue by projektorius96** [explainers-by-googlers/html-fullscreen-without-a-gesture#1]
**As titled** :
- [Feature requested by 3rd party, left with no faith](https://issues.chromium.org/issues/324520861)
- [The same feature requested by me@projektorius96, yet marked as obsolete](https://issues.chromium.org/u/1/issues/41491413)

If this is relevant, then I'd like to add that Microsoft Edge core team has implemented Shy UI, which is currently default UI for Fullscreen mode over same Chromium and it works so smoothly! The [Fullscreen mode toast button (X)](https://www.reddit.com/r/Diepio/comments/97nlnj/how_to_remove_chromes_x_dot_which_kicks_you_out/) should be at least controllable via flags, if not programmatically in Chrome.

Please keep in mind. This is year by year requesting by loyal Chrome users and definitely would contribute a lot to (Game) Developers experience, if pushed successfully !

---

If this DOES NOT encompass the specification draft, then at least please share your best offer to redirect this matter of concern. Thanks in advance, Nooglers !

**Comment by projektorius96** [comment]
I think I found [Borderless mode explainer](https://github.com/WICG/manifest-incubations/blob/gh-pages/borderless-explainer.md).

If anything to add, please re-open the issue.

**Comment by projektorius96** [comment]
As a random passer-by, I was kinda following this a bit and wanted to re-open discussion by adding a few remarks.

Currently the [Borderless mode](https://issues.chromium.org/issues/40781978) feature [is blocking](https://issues.chromium.org/u/1/issues/40781978#comment30) due to some [implementation bug of Desktop IWA (DPWA)](https://issues.chromium.org/issues/40225646) – in other words, as far as I do understand – once the IWA is implemented, Borderless mode is good to go as a feature.  
According to [this answer](https://issues.chromium.org/issues/40781978#comment30) the current status of Borderless mode also remains unknown. 

Also see [this discussion](https://issues.chromium.org/issues/41491413#comment5), and [this](https://issues.chromium.org/issues/324520861). Perhaps by upvoting the [later one](https://issues.chromium.org/issues/324520861), we could get more attention from Nooglers.

**Comment by michaelwasserman** [comment]
Upvoting the open Chromium issue [Feature Request: Hide (X) toast in fullscreen](http://crbug.com/324520861) is likely the best way to represent web developer sentiment regarding Chromium's implementation. Similarly, if the HTML Fullscreen Standard for for [FullscreenOptions "hide"](https://fullscreen.spec.whatwg.org/#dom-fullscreennavigationui-hide) is insufficient, I'd raise an issue there. Developers should convey their context and use cases for hiding those transient security-sensitive fullscreen UI elements, especially if it's not already reflected in existing open issues, or if a substantial number of users are adversely affected.

FWIW, this explainer (HTML Fullscreen Without a Gesture) directly cites UI overlays as a valuable trait in its [Security Considerations](https://github.com/explainers-by-googlers/html-fullscreen-without-a-gesture?tab=readme-ov-file#security-considerations).

Borderless mode is a separately proposed web application display mode that hides the window titlebar. Maximized borderless windows wouldn't show the transient fullscreen UI overlays, IIUC, but they would likely be constrained to the [available screen area](https://w3c.github.io/window-management/#concept-available-screen-area), i.e. not showing over OS taskbars. Discussion of Borderless mode feedback should be directed to the [WICG explainer](https://github.com/WICG/manifest-incubations/blob/gh-pages/borderless-explainer.md).

Please do reopen if I have misunderstood something, thanks!
